### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by marcusvinic2** [BlockHorizons/KillCounter#1]
Add /top Kill

**Comment by Sandertv** [comment]
I will, I will, it just isn't finished yet :P

**Comment by Sandertv** [comment]
Try the latest commit. It might have broken everything, not work, or other bad stuff, so good luck :P

**Comment by Sandertv** [comment]
All implemented. Works flawlessly.

**Comment by marcusvinic2** [comment]
Nice
